#!/usr/bin/env python3
"""
render_intent.py - turn detect_anomaly.py JSON into an intent.md DRAFT (Stage-1 format).

Closing the loop: a band breach re-enters the lifecycle as an intent that a
human (on-call / service owner) triages: fix now, schedule, or dismiss.
Dismissals are tuned in bands.yaml.

This script is deterministic templating — it records the evidence. The
diagnosis section is left for Claude (tier 2+) or a human to fill; when the
scheduled workflow invokes Claude it passes this draft as the starting point.

Usage
-----
    python render_intent.py detection.json                       # writes to stdout
    python render_intent.py detection.json --out work/anomaly-2026-08-27-ci-test-failure-rate/intent.md
    python detect_anomaly.py m.csv | python render_intent.py -   # read from stdin
Options:
    --author NAME     author line (default: "monitoring-bot (deterministic detector)")
    --owner NAME      product/service owner who triages (default: metric owner from bands.yaml)
    --force           render even when there is no active violation
Exit: 0 rendered; 3 nothing to render (no active violation and no --force).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence

TIER_TEXT = {
    0: "none",
    1: "Tier 1 (1 sigma) - log only",
    2: "Tier 2 (2 sigma) - read-only diagnosis",
    3: "Tier 3 (3 sigma) - may propose action via existing gates",
}


def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-") or "metric"


def _fmt(v: Any) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


def render(det: Dict[str, Any], author: str, owner: Optional[str] = None, force: bool = False,
           today: Optional[str] = None) -> Optional[str]:
    """Return the intent markdown, or None if there is nothing active to report."""
    active: List[Dict[str, Any]] = det.get("active_violations") or []
    if not active and not force:
        return None

    info = det.get("metric_info") or {}
    metric = det.get("metric", "metric")
    tier = int(det.get("highest_active_tier", 0))
    resp = det.get("response") or {}
    latest = det.get("latest") or {}
    params = det.get("parameters") or {}
    today = today or datetime.now(timezone.utc).date().isoformat()
    owner = owner or info.get("owner", "<service owner>")
    systems = info.get("affected_systems") or []
    evidence = active or det.get("violations") or []
    first_ts = min((v["start_timestamp"] for v in evidence), default=latest.get("timestamp", ""))
    int_id = f"INT-AUTO-{today.replace('-', '')}-{slugify(metric)}"

    lines: List[str] = []
    a = lines.append
    # ---- frontmatter: same keys as intent.template.md --------------------
    a("---")
    a(f"id: {int_id}")
    a(f'title: "Anomaly: {metric} breached control band ({TIER_TEXT.get(tier, tier)})"')
    a(f'author: "{author}"')
    a(f"created: {today}")
    a("status: draft")
    a(f'product_owner: "{owner}"')
    a('legacy_record: ""')
    a("source_of_truth: repo")
    a("links:")
    a('  spec: ""')
    a('  plan: ""')
    a(f'  origin: "monitoring:{metric}:{det.get("generated_at", "")}"')
    a("---")
    a("")
    a(f"# Anomaly: {metric}")
    a("")
    a("<!-- Generated by monitoring/render_intent.py from deterministic detection output.")
    a("     Triage: fix now | schedule | dismiss (dismissals -> tune monitoring/bands.yaml). -->")
    a("")
    # ---- Problem ------------------------------------------------------------
    a("## Problem")
    a("")
    desc = info.get("description") or metric
    a(f"`{metric}` ({desc}) left its control band starting {first_ts}. "
      f"Latest value {_fmt(latest.get('value'))} vs rolling baseline mean "
      f"{_fmt(latest.get('baseline_mean'))} (std {_fmt(latest.get('baseline_std'))}, "
      f"z = {_fmt(latest.get('z'))}). Highest active tier: **{TIER_TEXT.get(tier, tier)}**.")
    a("")
    # ---- Evidence -----------------------------------------------------------
    a("### Evidence")
    a("")
    a("| Rule | Meaning | Tier | Window | Peak value | Peak z | Active |")
    a("|---|---|---|---|---|---|---|")
    for v in evidence:
        pk = v.get("peak") or {}
        a(f"| {v['rule']} | {v['description']} | {v['tier']} | {v['start_timestamp']} -> {v['end_timestamp']} "
          f"| {_fmt(pk.get('value'))} | {_fmt(pk.get('z'))} | {'yes' if v.get('active') else 'no'} |")
    a("")
    a(f"Method: {det.get('method', 'rolling mean/std + Western Electric rules')}; "
      f"window {params.get('window')} points"
      + (f" ({params['baseline_label']})" if params.get("baseline_label") else "")
      + f", lookback {params.get('lookback')}. Source: {info.get('source', det.get('input', 'n/a'))}.")
    a("")
    # ---- Proposed outcome ---------------------------------------------------
    a("## Proposed outcome")
    a("")
    a(f"- `{metric}` returns inside its 1-sigma band and stays there for one full baseline window.")
    a("- Root cause identified and recorded in `lessons/`.")
    a("- A regression eval for this incident class is added to `evals/`.")
    a("")
    # ---- Affected ------------------------------------------------------------
    a("## Affected users and systems")
    a("")
    a("| Users / system | How affected | Owning team |")
    a("|---|---|---|")
    if systems:
        for s in systems:
            a(f"| {s} | metric `{metric}` out of band | {owner} |")
    else:
        a(f"| <system> | metric `{metric}` out of band | {owner} |")
    a("")
    # ---- Constraints ----------------------------------------------------------
    a("## Constraints")
    a("")
    a(f"- Response tier {tier}: action `{resp.get('action', 'none')}`.")
    if resp.get("tools"):
        a(f"- Agent tools for this tier (from bands.yaml): `{resp['tools']}`.")
    if resp.get("routes"):
        a(f"- Allowed action routes: {', '.join('`' + str(r) + '`' for r in resp['routes'])}. "
          "Any change arrives as a PR or a pre-approved runbook; nothing bypasses the review and production gates.")
    a("- Diagnosis is read-only unless the tier allows otherwise.")
    a("")
    # ---- Diagnosis placeholder ----------------------------------------------
    a("## Diagnosis")
    a("")
    a("<!-- Filled by Claude (tier >= 2) or the on-call engineer: likely cause, correlated")
    a("     deploys/merges, links to runs/logs. Keep evidence-first; mark guesses as guesses. -->")
    a("")
    # ---- Open questions ---------------------------------------------------------
    a("## Open questions")
    a("")
    a(f"- [ ] Is this a real regression or expected (e.g. planned change, holiday traffic)? - *who can answer:* {owner}")
    a("- [ ] Did a deploy or merge land inside the anomaly window? - *who can answer:* on-call")
    a("- [ ] Should the band be tuned if this is dismissed? - *who can answer:* service owner")
    a("")
    a("## Revision log")
    a("")
    a("| Date | Author | Change |")
    a("|---|---|---|")
    a(f"| {today} | {author} | Draft generated from band breach |")
    a("")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Render an intent.md draft from detect_anomaly.py output.")
    ap.add_argument("detection", help="detection JSON file, or '-' for stdin")
    ap.add_argument("--out", help="write markdown here (default stdout)")
    ap.add_argument("--author", default="monitoring-bot (deterministic detector)")
    ap.add_argument("--owner")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args(argv)

    raw = sys.stdin.read() if args.detection == "-" else open(args.detection, encoding="utf-8").read()
    det = json.loads(raw)
    md = render(det, author=args.author, owner=args.owner, force=args.force)
    if md is None:
        print("render_intent: no active violations; nothing to render (use --force to override)", file=sys.stderr)
        return 3
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(md)
        print(f"render_intent: wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
